package com.marketplace.authentication.domain.authorities;

public enum CustomerUserAuthority {
    CUSTOMER_READ_PRODUCT,
    CUSTOMER_CREATE_REVIEW,
    CUSTOMER_READ_REVIEW,
    CUSTOMER_UPDATE_REVIEW,
    CUSTOMER_DETELE_REVIEW,
    CUSTOMER_READ_FAVORITES_PRODUCT,
    CUSTOMER_CREATE_FAVORITE_PRODUCT,
    CUSTOMER_UPDATE_FAVORITE_PRODUCT,
    CUSTOMER_DELETE_FAVORITE_PRODUCT,
    CUSTOMER_READ_SHOPPING_CART,
    CUSTOMER_ADD_TO_SHOPPING_CART,
    CUSTOMER_DELETE_FROM_SHOPPING_CART,
    CUSTOMER_MAKE_AN_ORDER;
}
